using System.Runtime.InteropServices;

namespace StructPolymorphismGenerator.Sample;

enum MissionType
{
    Defense,
    Annihilation
}


[System.AttributeUsage(System.AttributeTargets.Struct)]
public class HeaderAttribute : System.Attribute
{
}

[System.AttributeUsage(System.AttributeTargets.Property)]
public class HeaderElementAttribute : System.Attribute
{
}
[System.AttributeUsage(System.AttributeTargets.Interface)]
public class AbstractStructGeneratorAttribute : System.Attribute
{
}
[Header]
struct MissionHeader
{
    public MissionType Type;
    public int MissionId;
}

[AbstractStructGenerator]
interface IMissionable
{
    MissionHeader Header { get; }
    [HeaderElement] MissionType Type { get; }

    bool IsMissionComplete();
}

partial struct Mission : IMissionable
{
    public MissionHeader Header { get; }

    public MissionType Type => Header.Type;

    public bool IsMissionComplete()
    {
        unsafe
        {
            fixed (Mission* mission = &this)
            {
                return mission->Type switch
                {
                    MissionType.Defense => ((DefenseMission*) mission)->IsMissionComplete(),
                    MissionType.Annihilation => ((AnnihilationMission*) mission)->IsMissionComplete(),
                    _ => false
                };
            }
        }
    }
}

#region MissionAutoGenerated
partial struct DefenseMission : IMissionable
{
    public MissionHeader Header { get; }

    public MissionType Type => Header.Type;
}
partial struct AnnihilationMission : IMissionable
{
    public MissionHeader Header { get; }
    
    public MissionType Type => Header.Type;
} 
#endregion

#region UserCode



partial struct DefenseMission
{
    public bool IsMissionComplete()
    {
        //時間経過とか
        return true;
    }
}


partial struct AnnihilationMission
{
    public bool IsMissionComplete()
    {
        //残ってる敵の数とか
        return true;
    }
} 

#endregion

public class StructPolymorphismSExample
{
    
}